version: "2"
services:
  test-db:
    build:
      context: .
      dockerfile: test/Dockerfile-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "25432:5432"
    shm_size: 1gb

  test:
    build:
      context: .
      dockerfile: test/Dockerfile-test
    volumes:
      - ./:/opt/test
    environment:
      PGNAME: conflate
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGDATABASE: test
    command: /bin/bash -c "cd /opt/test && make import-db"
